### ISSUE TITLE
field guessing bug

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormDB#111]
In variableSet.py, there's a bug where the intent isn't clear enough for me to fix. At [L94](https://github.com/Bookworm-project/BookwormDB/blob/master/bookwormDB/variableSet.py#L94):

```
    if type(example) == list:    
        unique(example) == False 
```

This might simply be left over from refactoring, as suggested by the orphan `maxEntries` a few lines later. Or it's dummy code: it looked right to me because I'm so used to R, but my linter pointed out that Python doesn't have `unique`.

**Comment by bmschmidt** [comment]
Yes, that looks like a place I was programming in R, not python.

Looking at the code, I'm pretty sure that the actual goal was to set, not test, a dictionary entry: that is,

```
descriptions['unique'] = False
```

Odd that this never threw an error. Possibly it's because I've never run the guessing script (which is pretty esoteric, still) on data with a multiple-keyed field.

I should add some unit tests for the guessing code. But I'm not sure if it officially even exists.
