### ISSUE TITLE
Arabic tokenization doesn't work

### ISSUE THREAD

**Issue by bmschmidt** [Bookworm-project/BookwormDB#123]
The new unicode tests show that things are mostly working in unicode. But I noticed one problem.

The token regex is designed for languages I speak; it gets increasingly out of whack the farther you get from them.

It's probably basically broken on Japanese or Chinese; I would suggest pre-parsing Japanese or Chinese text to be space-separated before inputting into a bookworm. 

But it's also failing on Arabic, where it should have a fighting chance. The first line of Quran is ending up as 29 words, which seems probably too long; many "words" are only a character or so. (Though I dunno, maybe that's how Arabic looks).

If there are Arabic speakers out there, I'm curious where things are going wrong. Below It looks to me like possibly it's splitting at some kind of inflection character, or something of the sort? (Each line, it thinks, is a "word" in Arabic.)

It may be that some inflection characters aren't technically instances of unicode 'p{L}', but should be allowed to occur inside words?

EDIT--I notice there's an english "u" lurking around inside the Arabic verse. That's because my terminal is borking up on the Arabic; but it doesn't seem to be affecting the core problem here.

```
In [1]: import bookwormDB.tokenizer

In [2]: verse = u"بِسْمِ اuللَّـهِ الرَّحْمَـٰنِ الرَّحِيمِ"

In [3]: tokens = bookwormDB.tokenizer.tokenizer(verse).tokenize()

In [4]: for token in tokens: print token
ب
ِ
س
ْ
م
ِ
اuلل
ّ
َ
ـه
ِ
الر
ّ
َ
ح
ْ
م
َ
ـ
ٰ
ن
ِ
الر
ّ
َ
ح
ِ
يم
ِ
```

**Comment by Whadup** [comment]
judging by this, the first verse should have 4 tokens: http://corpus.quran.com/treebank.jsp?chapter=1&verse=1

**Comment by Whadup** [comment]
I've asked a native speaker, it really should output 4 tokens.

**Comment by organisciak** [comment]
Here's a few tokens to potentially add to your tests: 'मे', 'है', 'नही',
'होत', 'जात', 'किय', 'लिए', 'मै', 'हुए', 'कुछ', 'रूप', 'हुआ', 'हैं', 'दिय',
'होन', 'मेर', 'किस', 'कोई', 'साथ',  'जान', 'प्रकार', 'लिय', 'बात', 'वाल',
'हुई', 'क्य', 'फिर', 'द्वार', 'जैस', 'कारण', 'देत', 'जीवन', 'बहुत', 'देख',
'नाम', 'मुझ', 'होग'.

I'm not sure if this pertains to Bookworm, but I've had Python `re` stumble
over word characters that consist of two codepoints, as in Hindi and
Punjabi. It does not consider them word characters (i.e. \w) and fails
isalpha(). The 'regex' module has better support, which BW uses in most
places.



On Wed, Jan 25, 2017 at 8:19 AM Whadup <notifications@github.com> wrote:

I've asked a native speaker, it really should output 4 tokens.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Bookworm-project/BookwormDB/issues/123#issuecomment-275135563>,
or mute the thread

**Comment by bmschmidt** [comment]
Peter- Could you give a little more background of what these tokens are? Hindi?

So we need some tests, and then we need a regex that enforces the test.

It is clear that the catchall regex here: `\p{L}+` is not catching some class of characters in Hindi and Arabic. But I don't understand these scripts well enough to fix this, so we need someone who speaks the language and can look up some regex class codes in them. It may be that there's a group capture for all inflection characters or something; it might be that there are just five or ten codepoints that would cover language spoken by a significant fraction of the world's population (if we're having trouble with Arabic and Hindi).

It's possible that we need language-aware tokenization rules. I would really rather not adopt this strategy, because language metadata and detection is very frequently wrong, particularly in historical documents.

```python
import regex as re
token_regex = re.compile("\\p{L}+",re.UNICODE|re.IGNORECASE)
tokens = ['मे', 'है', 'नही', 'होत', 'जात', 'किय', 'लिए', 'मै', 'हुए', 'कुछ', 'रूप', 'हुआ', 'हैं', 'दिय', 'होन', 'मेर', 'किस', 'कोई', 'साथ',  'जान', 'प्रकार', 'लिय', 'बात', 'वाल', 'हुई', 'क्य', 'फिर', 'द्वार', 'जैस', 'कारण', 'देत', 'जीवन', 'बहुत', 'देख', 'नाम', 'मुझ', 'होग']
tokens = [t.decode("utf-8") for t in tokens]
tokenized = re.findall(token_regex,u" ".join(tokens))
print len(tokens)
print len(tokenized)
```

**Comment by organisciak** [comment]
These are Sanskrit, Hindi looked similar but is less common. They're the top tokens in Extracted Features, and I don't know if they were properly tokenized to begin with.


The problem here seems to be what I encountered: that there are more code points per character than typical, because some glyphs use multiple 'characters' that can't be understood in isolation. In my case, re wasn't looking at the whole sequence when I asked for a character-based evaluation like \w. e.g. `'है'.encode('utf-8')` is `b'\xe0\xa4\xb9\xe0\xa5\x88'`, but `re` treated that as two characters, the second of which is not a word character to match '\w'. `regex` got it correct, but in your case, seems to be failing.

You can see hints at this with your code by looking at the bytes. This is Python 3, you'll have to modify for 2:

```python
for token in tokens:
    print(token, "\t", token.encode('utf-8'))
    
    tokenized = re.findall(token_regex, token)
    tokenized_codepoints = [str(t.encode('utf-8')) for t in tokenized]
    print(" ".join(tokenized), "\t", " ".join(tokenized_codepoints), '\n')
```

```
मे 	 b'\xe0\xa4\xae\xe0\xa5\x87'
म 	 b'\xe0\xa4\xae'

है 	 b'\xe0\xa4\xb9\xe0\xa5\x88'
ह 	 b'\xe0\xa4\xb9'

नही 	 b'\xe0\xa4\xa8\xe0\xa4\xb9\xe0\xa5\x80'
नह 	 b'\xe0\xa4\xa8\xe0\xa4\xb9'

होत 	 b'\xe0\xa4\xb9\xe0\xa5\x8b\xe0\xa4\xa4'
ह त 	 b'\xe0\xa4\xb9' b'\xe0\xa4\xa4'

जात 	 b'\xe0\xa4\x9c\xe0\xa4\xbe\xe0\xa4\xa4'
ज त 	 b'\xe0\xa4\x9c' b'\xe0\xa4\xa4'

किय 	 b'\xe0\xa4\x95\xe0\xa4\xbf\xe0\xa4\xaf'
क य 	 b'\xe0\xa4\x95' b'\xe0\xa4\xaf'

लिए 	 b'\xe0\xa4\xb2\xe0\xa4\xbf\xe0\xa4\x8f'
ल ए 	 b'\xe0\xa4\xb2' b'\xe0\xa4\x8f'

मै 	 b'\xe0\xa4\xae\xe0\xa5\x88'
म 	 b'\xe0\xa4\xae'

हुए 	 b'\xe0\xa4\xb9\xe0\xa5\x81\xe0\xa4\x8f'
ह ए 	 b'\xe0\xa4\xb9' b'\xe0\xa4\x8f'

कुछ 	 b'\xe0\xa4\x95\xe0\xa5\x81\xe0\xa4\x9b'
क छ 	 b'\xe0\xa4\x95' b'\xe0\xa4\x9b'

रूप 	 b'\xe0\xa4\xb0\xe0\xa5\x82\xe0\xa4\xaa'
र प 	 b'\xe0\xa4\xb0' b'\xe0\xa4\xaa'

हुआ 	 b'\xe0\xa4\xb9\xe0\xa5\x81\xe0\xa4\x86'
ह आ 	 b'\xe0\xa4\xb9' b'\xe0\xa4\x86'
```

And so on. Note that it is matching three codepoints at a time. For example, for b'\xe0\xa4\xb9\xe0\xa5\x81\xe0\xa4\x86', it looked at b'\xe0\xa4\xb9', b'\xe0\xa5\x81', b'\xe0\xa4\x86', and the middle one didn't match.

```python
for seq in [b'\xe0\xa4\xb9', b'\xe0\xa5\x81', b'\xe0\xa4\x86']:
    char = seq.decode('utf-8')
    print(char, "matched" if re.match(token_regex, char) else "didn't match")
```

```
ह matched
ु didn't match
आ matched
```

The middle character simply adds that little tail to the first character, and is being stripped out. Try pasting ु once or twice after ह and you'll get हु then हुु.

This seems like a problem that English speakers shouldn't be trying to figure out: surely it's been discussed ad nauseum somewhere?

**Comment by organisciak** [comment]
Here's a more to-the-point demonstration: just split on each individual character. It seems `\w` in *particular* was fixed in regex, but not `\p{L}`. Using original module names:

```
regex.findall("\\p{L}", 'नही')
>> ['न', 'ह']

regex.findall("\w", 'नही')`
>>  ['न', 'ह', 'ी']

re.findall("\w", 'नही')`
>> ['न', 'ह']
```

**Comment by bmschmidt** [comment]
Thanks @organisciak, very helpful info.

Agree that this is mostly fumbling in the dark without informed input. But it seems there would be real benefits to just switching to `\\w` instead of `\\p{L}`, on Arabic as well. I'll give it a shot.

Also noting this appears to be a moving target. [According to the regex page,](https://pypi.python.org/pypi/regex/2016.10.22) as of 2016-10 "The definition of a ‘word’ character has been expanded for Unicode. It now conforms to the Unicode specification at http://www.unicode.org/reports/tr29/. This applies to \w, \W, \b and \B."

So everyone should be sure to update their version of regex.

```python
verse = u"بِسْمِ اللَّـهِ الرَّحْمَـٰنِ الرَّحِيمِ"
​
for token in regex.findall(token_regex, verse):
    print token
​
بِسْمِ
اللَّـهِ
الرَّحْمَـٰنِ
الرَّحِيمِ

```

**Comment by bmschmidt** [comment]
OK, the switch to `r"\w"` is pushing Arabic as four tokens and should do Sanskrit the way Peter lays out.

I'm sure our unicode compatibility is not perfect, and I'd welcome expansions of the base regex for other languages.

But I'm going to close this issue for now.
