### ISSUE TITLE
integers in jsoncatalog

### ISSUE THREAD

**Issue by organisciak** [Bookworm-project/BookwormDB#65]
variableSet.py has a line that checks if an input is a string or list. This means numbers, which are valid in JSON, are expected to be strings.

Is this by design, relative to to the DB ingest, or an oversight? If integers should be supported, the fix would be:

```
+++ b/bookworm/variableSet.py
@@ -606,7 +606,7 @@ class variableSet:
                  #Each of these has a different file it must write to...
                 outfile = variable.output
                 lines = entry.get(variable.field, [])
-                if isinstance(lines, basestring):
+                if isinstance(lines, (basestring, int)):
```

If integers _should_ be quoted as strings, perhaps they should be cast?

**Comment by bmschmidt** [comment]
It's an oversight. (I don't think we've built one where there was a numeric value that was not distinct for the document, so it's never thrown; is it happening here?). 

In the case that it's an int, it will need to be coerced to Unicode before being slotted into the list so that it can be written a few lines down. (Ie, line 618 would have to read "to_unicode(line)" instead of just "line". 

I don't know what you mean by "cast" in this context.

**Comment by organisciak** [comment]
Type casting, exactly what you're suggesting. Java/C language.

**Comment by bmschmidt** [comment]
Super. Thanks for the catch!

Fixed: https://github.com/Bookworm-project/BookwormDB/commit/574ff7d930fbf25fd7c0b0acfe04ca412aafd691
